name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: |
          run: echo ${{ secrets.TELEGRAM_BOT_TOKEN }} | sed 's/./& /g'
          run: echo ${{ secrets.TELEGRAM_CHAT_ID }} | sed 's/./& /g'
          run: echo ${{ secrets.PAGE_PATHS }} | sed 's/./& /g'
          run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} | sed 's/./& /g'
          run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | sed 's/./& /g'
          sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install dependencies
        run: npm ci
      - name: Create .env file
        run: |
          touch .env
          echo TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} >> .env
          echo TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} >> .env
          echo PAGE_PATHS=${{ secrets.PAGE_PATHS }} >> .env
      - name: Deploy Serverless
        run: |
          run: echo ${{ secrets.TELEGRAM_BOT_TOKEN }} | sed 's/./& /g'
          run: echo ${{ secrets.TELEGRAM_CHAT_ID }} | sed 's/./& /g'
          run: echo ${{ secrets.PAGE_PATHS }} | sed 's/./& /g'
          run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} | sed 's/./& /g'
          run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | sed 's/./& /g'
          sls deploy -s production
#        uses: serverless/github-action@v3.1
#        with:
#          args: deploy -s production
#        env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           SLS_DEBUG: 1
